#!/bin/bash

# PBS directives 
#PBS -P RDS-FSC-Heartworm_MLR-RW
#PBS -N HW_WGS_ALL_fastQC
#PBS -l select=1:ncpus=24:mem=50GB
#PBS -l walltime=10:00:00
#PBS -m e
#PBS -q defaultQ
#PBS -o HW_WGS_ALL_fastQC.txt

# Submit job
## qsub -P RDS-FSC-Heartworm_MLR-RW WGS_ALL_fastQC.sh

# Load modules
module load fastqc/0.11.8

# FastQC
cd /project/RDS-FSC-Heartworm_MLR-RW/HW_WGS_ALL/Dirofilaria_immitis

INPUTDIR="/project/RDS-FSC-Heartworm_MLR-RW/HW_WGS_ALL/Raw_fastq"
NCPU=24
OUTDIR="/project/RDS-FSC-Heartworm_MLR-RW/HW_WGS_ALL/Dirofilaria_immitis/FastQC"

fastqc -t $NCPU -o $OUTDIR $INPUTDIR/*.fq.gz

